import {
  Sparkles,
  Palette,
  CreditCard,
  Tag,
  Sticker,
  BadgeCheck,
  Copy,
  PenLine,
  Shirt,
  Box,
  Flag,
  Megaphone,
  Award,
  LayoutTemplate,
  Stamp,
  Car,
  Building2,
  Image,
  Layers,
  Book,
  BookOpen,
  CupSoda,
  Umbrella,
  Gift,
  Mail,
  Paintbrush,
  Route,
  Mountain,
  Trophy,
  FileText,
  Frame,
  Camera,
  Film,
  Monitor,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  palette: Palette,
  creditCard: CreditCard,
  tag: Tag,
  sticker: Sticker,
  badgeCheck: BadgeCheck,
  copy: Copy,
  penLine: PenLine,
  shirt: Shirt,
  cube: Box,
  flag: Flag,
  megaphone: Megaphone,
  award: Award,
  layout: LayoutTemplate,
  stamp: Stamp,
  car: Car,
  building2: Building2,
  image: Image,
  layers: Layers,
  book: Book,
  bookOpen: BookOpen,
  cupSoda: CupSoda,
  umbrella: Umbrella,
  gift: Gift,
  mail: Mail,
  paintbrush: Paintbrush,
  route: Route,
  mountain: Mountain,
  trophy: Trophy,
  fileText: FileText,
  frame: Frame,
  camera: Camera,
  film: Film,
  monitor: Monitor,
};

export function iconFor(name: string) {
  const Icon = iconMap[name] ?? Sparkles;
  return <Icon size={24} strokeWidth={1.5} />;
}